import { fetchBriefing, fetchGeoTIFF, fetchReport } from "../api/exports";
import type { BriefingParams } from "../api/exports";
import type { BBox } from "../types/map";

export interface ExportSource {
  analysis_type: string;
  display_name: string;
  bbox: BBox;
  start_date: string;
  end_date: string;
  data_date: string;
  confidence: number;
  headline_label: string;
  headline_value: number;
  headline_unit: string;
  stats?: Record<string, unknown>;
}

function triggerDownload(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export async function downloadGeoTIFF(src: ExportSource): Promise<void> {
  const res = await fetchGeoTIFF({
    analysis_type: src.analysis_type,
    bbox: src.bbox,
    start_date: src.start_date,
    end_date: src.end_date,
  });
  window.open(res.download_url, "_blank", "noopener");
}

function escapeXml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function downloadKML(
  src: ExportSource,
  polygon?: [number, number][] | null
): void {
  const ring: [number, number][] = polygon?.length
    ? polygon
    : [
        [src.bbox[0], src.bbox[1]],
        [src.bbox[2], src.bbox[1]],
        [src.bbox[2], src.bbox[3]],
        [src.bbox[0], src.bbox[3]],
      ];
  const closed = [...ring, ring[0]];
  const coords = closed.map(([lon, lat]) => `${lon},${lat},0`).join(" ");
  const name = escapeXml(`${src.display_name} · ${src.data_date}`);
  const description = escapeXml(
    `${src.headline_label}: ${src.headline_value} ${src.headline_unit}\n` +
      `Confidence: ${Math.round(src.confidence * 100)}%\n` +
      `Window: ${src.start_date} to ${src.end_date}\n` +
      `Latest Sentinel-1 pass: ${src.data_date}\n` +
      `Generated by Kairos from Copernicus Sentinel-1 data via Google Earth Engine.`
  );
  const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${name}</name>
    <Style id="kairos">
      <LineStyle><color>ffa8bf00</color><width>2</width></LineStyle>
      <PolyStyle><color>33a8bf00</color></PolyStyle>
    </Style>
    <Placemark>
      <name>${name}</name>
      <description>${description}</description>
      <styleUrl>#kairos</styleUrl>
      <ExtendedData>
        <Data name="analysis_type"><value>${escapeXml(src.analysis_type)}</value></Data>
        <Data name="${escapeXml(src.headline_label)}"><value>${src.headline_value} ${escapeXml(src.headline_unit)}</value></Data>
        <Data name="confidence"><value>${src.confidence}</value></Data>
        <Data name="data_date"><value>${escapeXml(src.data_date)}</value></Data>
      </ExtendedData>
      <Polygon>
        <outerBoundaryIs><LinearRing><coordinates>${coords}</coordinates></LinearRing></outerBoundaryIs>
      </Polygon>
    </Placemark>
  </Document>
</kml>`;
  triggerDownload(
    `kairos_${src.analysis_type}_${src.data_date}.kml`,
    kml,
    "application/vnd.google-earth.kml+xml"
  );
}

export async function openBriefing(params: BriefingParams): Promise<void> {
  const res = await fetchBriefing(params);
  const blob = new Blob([res.html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  window.open(url, "_blank", "noopener");
  setTimeout(() => URL.revokeObjectURL(url), 60000);
}

export async function downloadReport(src: ExportSource): Promise<void> {
  const res = await fetchReport({
    analysis_type: src.analysis_type,
    display_name: src.display_name,
    bbox: src.bbox,
    start_date: src.start_date,
    end_date: src.end_date,
    data_date: src.data_date,
    confidence: src.confidence,
    headline_label: src.headline_label,
    headline_value: src.headline_value,
    headline_unit: src.headline_unit,
    stats: src.stats,
  });
  triggerDownload(res.filename, res.markdown, "text/markdown");
}
